### ISSUE TITLE
[Bug] API fails to boot (Error: Cannot find module 'back-end/src/enterprise')

### ISSUE THREAD

**Issue by Marcos-Rgz** [growthbook/growthbook#4345]
### Summary

By following the steps provided in [Open source](https://github.com/growthbook/growthbook?tab=readme-ov-file#open-source) section of Readme.md:

```bash
git clone https://github.com/growthbook/growthbook.git
cd growthbook
docker-compose up -d
```
I expect to be able to access the welcome page, but I'm getting an error instead

#### Expected Behavior

- The platform boots correctly
- I can access the welcome screen in http://localhost:3000

#### Current Behavior

- API is not booting correctly in latest version
- Everything works fine in v3.6.0

#### Screenshots

<img width="797" height="942" alt="Image" src="https://github.com/user-attachments/assets/dec608d5-44d6-41eb-a395-5e2dd8a63da1" />

<img width="573" height="356" alt="Image" src="https://github.com/user-attachments/assets/3905d289-dacb-4879-9c32-7f1adbf4f99f" />
